{"uid":"40b61964074fe550","name":"setUp","fullName":"testClassPool.LoanJourneyDatabaseValidationTest.setUp","historyId":"a4c67951e9837bb58b02b9e32ed2b0f9","time":{"start":1751437709924,"stop":1751437709924,"duration":0},"status":"broken","statusMessage":"Database connection failed","statusTrace":"java.lang.RuntimeException: Database connection failed\n\tat utils.DatabaseUtils.initializeConnection(DatabaseUtils.java:55)\n\tat testClassPool.LoanJourneyDatabaseValidationTest.setUp(LoanJourneyDatabaseValidationTest.java:22)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\n\tat org.testng.TestRunner.run(TestRunner.java:616)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\nCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)\n\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)\n\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)\n\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)\n\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:682)\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)\n\tat utils.DatabaseUtils.initializeConnection(DatabaseUtils.java:50)\n\t... 19 more\nCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\tat java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)\n\tat com.mysql.cj.NativeSession.connect(NativeSession.java:121)\n\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)\n\t... 25 more\nCaused by: java.net.UnknownHostException: devdb-ujwy3me96v.stashfin.com: nodename nor servname provided, or not known\n\tat java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)\n\tat java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)\n\tat java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1221)\n\tat java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1817)\n\tat java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1149)\n\tat java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1807)\n\tat java.base/java.net.InetAddress.getAllByName(InetAddress.java:1676)\n\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:130)\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)\n\t... 28 more\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"package","value":"testClassPool.LoanJourneyDatabaseValidationTest"},{"name":"testClass","value":"testClassPool.LoanJourneyDatabaseValidationTest"},{"name":"testMethod","value":"setUp"},{"name":"parentSuite","value":"Stashfin Web Automation Suite"},{"name":"suite","value":"Stashfin Web Test Run"},{"name":"subSuite","value":"testClassPool.LoanJourneyDatabaseValidationTest"},{"name":"host","value":"MacBook-Pro.local"},{"name":"thread","value":"19907@MacBook-Pro.local.TestNG-tests-1(47)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"AS_ID","value":"-1"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"40b61964074fe550.json","parameterValues":[]}